id: A1323C712
title: Prayer to Butön Rinpoche
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:41:32.651515
  last_modified_at: 2022-02-28 22:41:32.651527
